name: raven-hydro
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.15
  - pip >=25.2
  - hatch-fancy-pypi-readme >=25.1.0
  - hatchling >=1.27.0
  - pybind11 >=3.0.1
  - scikit-build-core >=0.11
  - setuptools-scm >=9.2
  - hdf5
  - libnetcdf
  - zlib
